let guests2 = ["khizer","muneeb","anus","Hassan","Sarah","Sana"];
console.log("we can invite only two guests");
guests2.pop();
guests2.pop();
guests2.pop();
guests2.pop();
guests2.pop();
guests2.pop();
//console.log(guests2[0]);
//console.log(guests2[1]);
console.log("sorry anus we can't invite you to dinner");
console.log("sorry Hassan we can't invite you to dinner");
console.log("sorry Sarah we can't invite you to dinner");
console.log("sorry Sana we can't invite you to dinner");